# Generated by Django 3.2.16 on 2023-04-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_rename_job_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='job',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='job_type',
            new_name='shop_type',
        ),
        migrations.DeleteModel(
            name='BookmarkJob',
        ),
    ]
