# Generated by Django 3.2.16 on 2023-04-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_auto_20230426_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='salary',
            new_name='avg_spend',
        ),
    ]
